--- 
:boxes:
  :ccvm1: 
    :ip: 10.0.3.150
    # clusterip
    :local_node: "1"
  :ccvm2: 
    :ip: 10.0.3.151
    # clusterip
    :local_node: "2"
  :ccvm3: 
    :ip: 10.0.3.152
    # clusterip
    :local_node: "3"
:test:
  :number: "3"
  :flag: true
  :some: value

